### PR TITLE
Minor improvements for drupal.org project release.

### PR DESCRIPTION
**Pull request by mstenta**

### CODE REVIEW

**Comment by mstenta** [comment]
I created the drupal.org project: https://www.drupal.org/project/restws_oauth2_server

We can push to that once we're ready.

**Comment by paul121** [comment]
@mstenta thanks for looking over this! Sorry I had a few mistakes I should have caught in there.

`watchdog()` logs messages to reports->recent log messages? That is much better.

We might not want to log all errors for unauthenticated tokens here - 4d6b98dc2ffde6d9d878207117f9c7c8b4d6b50e This would log for all anonymous requests, including an anonymous user just browsing pages on a Drupal site. For farmOS this wouldn't be a problem, but may be a problem for others? What do you think?

Other than that just had to make one change in 6f58b43c0989c974c6469cb49bf22dd6307fd702

**Comment by mstenta** [comment]
Sure thing! It's a nice simple module. Straight and to the point. :-)

> `watchdog()` logs messages to reports->recent log messages? That is much better.

Yea `watchdog()` is Drupal's internal logging functions (as opposed to `drupal_set_message()` which prints to the user on the next page load, but is not stored anywhere). Watchdog is part of the core Drupal system module (I believe) and doesn't actually do anything with the log messages itself, but Drupal comes with two other (optional) modules that hook in and provide storage for the logs: `dblog` (which saves to a database table and provides /admin/reports/dblog aka "Recent log messages") and `syslog` (which saves to /var/log/syslog).

> We might not want to log all errors for unauthenticated tokens here - 4d6b98d This would log for all anonymous requests, including an anonymous user just browsing pages on a Drupal site. For farmOS this wouldn't be a problem, but may be a problem for others? What do you think?

Oh you're right. We shouldn't do that. :-)

Is there any way we can check if OAuth headers are set early in that `hook_init`? And if they aren't, `return;` before we get to the call to `oauth2_server_check_access()`). I'm not sure how much is happening in that function... but if we don't need to run it, we shouldn't.

That would allow us to leave the `watchdog()` call in, knowing that it would only run if an OAuth request is being made.

Would that work? Or am I missing anything? Are there standard headers we can look for?

**Comment by paul121** [comment]
I'll add `watchdog()` to my Drupal toolbelt, then! Thanks.

> Is there any way we can check if OAuth headers are set early in that hook_init?

There would be an `Authentication` header with a value such as `Bearer 123456789` whenever a request with a token is submitted.

I remember trying to look into how to get the headers before we found the `restws` solution for authenticating users, but didn't get too far. I think that would work though - we could just check if there is an `Authentication` header with a `Bearer` token.

**Comment by mstenta** [comment]
> There would be an `Authentication` header with a value such as `Bearer 123456789` whenever a request with a token is submitted.

Great!  So maybe something like:

```
function restws_oauth2_server_init() {

  // If an authorization header is not set, bail.
  if (empty($_SERVER['HTTP_Authorization'])) {
    return;
  }

  ...
```

I'm not sure if `$_SERVER['HTTP_Authorization'])` is correct... but probably something like that.

**Pull request merged**
